---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=9091
      - TORRENTING_PORT=6881
    volumes:
      - /home/administrador/docker/qbittorrent/config:/config
      - /mnt/nas/dockerdata/qbittorrent/downloads:/downloads #optional
    ports:
      - 9091:9091
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
