services:
  app:
    build:
      target: dev
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    container_name: app
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # CAMBIO: Ahora monta el código fuente local, igual que el webserver.
      - ./:/var/www/cocktails
      # NUEVO: Monta la carpeta del NAS para datos persistentes en la carpeta de storage.
      - /mnt/nas/dockerdata/barassistant/storage:/var/www/cocktails/storage
      - ./resources/docker/localdev/php.ini:/usr/local/etc/php/conf.d/zzz-xbass-php.ini

  horizon:
    build:
      target: dev
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    restart: unless-stopped
    environment:
      APP_ROLE: "worker"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["php", "/var/www/cocktails/artisan", "horizon"]
    volumes:
      # CAMBIO: Ahora monta el código fuente local.
      - ./:/var/www/cocktails
      # NUEVO: Monta también la carpeta de storage para consistencia.
      - /mnt/nas/dockerdata/barassistant/storage:/var/www/cocktails/storage
      - ./resources/docker/localdev/php.ini:/usr/local/etc/php/conf.d/zzz-xbass-php.ini

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 3000:80
    volumes:
      # Esto ya estaba correcto, se mantiene igual.
      - ./:/var/www/cocktails
      - ./resources/docker/localdev/nginx.conf:/etc/nginx/conf.d/default.conf

  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped

  meilisearch:
    image: getmeili/meilisearch:v1.11
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=QuU5HWvl4XkQ0GBv5genEFPE5KnsLIv5
    restart: unless-stopped
    ports:
      - 7700:7700
    volumes:
      - meilidata:/meili_data

  metrics:
    image: prom/prometheus
    volumes:
      - ./resources/docker/localdev/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

volumes:
  meilidata:
  miniiodata:
