services:
  mylar3:
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylar3
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/administrador/docker/mylar3/config:/config
      - /mnt/nas/dockerdata/mylar3/comics:/comics
      - /mnt/nas/dockerdata/mylar3/downloads:/downloads
    ports:
      - 8090:8090
    restart: unless-stopped
