name: spotizerr
services:
  spotizerr:
    volumes:
      - /home/administrador/docker/spotizerr:/app/data
      - /home/administrador/docker//config:/app/config
      - /mnt/nas/dockerdata/spotizerr/downloads:/app/downloads
      - /home/administrador/docker/logs:/app/logs
    ports:
      - 7171:7171
    image: lavaforge.org/spotizerr/spotizerr:latest
    container_name: spotizerr-app
    environment:
#      - PUID=1000  # podman rootless needs PUID=0, or removed like this
#      - PGID=1000  # podman rootless needs PGID=0, or removed like this
      - UMASK=0002  # allow all users in media group to access music downloaded by spotizerr
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_URL=redis://redis:6379/0
      - REDIS_BACKEND=redis://redis:6379/0
      - EXPLICIT_FILTER=false # Set to true to filter out explicit content
    depends_on:
      - redis
    networks:
      - spotizerr-net

  redis:
    image: redis:alpine
    container_name: spotizerr-redis
    volumes:
      - redis-data:/data
